### ISSUE TITLE
Duplicate Paragraph

### ISSUE THREAD

**Issue by ashleyhomen** [learn-co-curriculum/js-looping-and-iteration-filter-lab#5]
Following paragraph is duplicated

USE FILTER TO WORK WITH STRINGS AS WELL AS OBJECTS
This lab contains an array of drivers with various information. We need to write methods using the filter method so that Scuber employees can easily query the data. Be sure to run the tests to get a feel for the types of problems this lab is asking you to solve before you start writing JavaScript code.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

Thank you for your contribution 💙
